### ISSUE TITLE
Clarify home of the project

### ISSUE THREAD

**Issue by sebasmagri** [adammck/pygsm#4]
[tmcw/slingshotsms](http://github.com/tmcw/slingshotsms) has an internal copy of pygsm and [rapidsms/pygsm](http://github.com/rapidsms/pygsm) seems to be a fork, both were updated after the last update in this repo. Which one should I clone/fork?

**Comment by adammck** [comment]
rapidsms/pygsm is fresher than this repo, and includes support for PDU messages. you should probably use it, but i haven't deleted this repo, because i'm not very happy about the quality of the refactoring.

tmcw/slingshotsms wraps pygsm, and provides a nice REST interface to it. it's a separate project.
